"""Build the guarded native camera variant from the current generated routine.

Keep the recompiler's continuations, cycle accounting and interrupt handling.
Eight horizontal focal operands change, and the combat yaw is captured for
source-facing conditions. Vertical fit and the guest projection registers
stay original. Fail the build if code generation changes
an expected instruction or expression. Guest executable RAM is never patched.
"""
import argparse
from pathlib import Path
import struct

SITES = {
    0x80065448: 0x00920018,
    0x80065468: 0x00720018,
    0x8006548C: 0x00920018,
    0x800654AC: 0x00720018,
    0x80065504: 0x02420018,
    0x800655D0: 0x0052001A,
    0x8006565C: 0x0052001A,
    0x80065684: 0x0052001A,
}


def generate(source: str, exe: bytes) -> str:
    load_address = struct.unpack_from('<I', exe, 0x18)[0]
    for address, word in SITES.items():
        actual = struct.unpack_from('<I', exe, address - load_address + 0x800)[0]
        if actual != word:
            raise ValueError(f'Camera instruction mismatch at {address:08X}')
    start = source.index('void func_80064E10(CPUState* cpu)\n{')
    end = source.index('\n}\n', start) + 3
    body = source[start:end].replace('void func_80064E10(', 'void __wrap_func_80064E10(', 1)
    marker='/* 0x80064E20: 0x00E0F021 */'
    if body.count(marker)!=1 or struct.unpack_from('<I',exe,0x80064e20-load_address+0x800)[0]!=0x00e0f021:
        raise ValueError('Camera yaw instruction mismatch')
    body=body.replace(marker,marker+'\n    tekken3_fight_camera_capture_yaw(cpu);')
    for address, word in SITES.items():
        marker = f'#endif  /* 0x{address:08X}: 0x{word:08X} */'
        if body.count(marker) != 1:
            raise ValueError(f'Camera generated marker mismatch at {address:08X}')
        pos = body.index(marker)
        statement_end = body.rfind('\n#ifdef PSX_ENABLE_BLOCK_CYCLES', 0, pos)
        statement_start = body.rfind('\n', 0, statement_end) + 1
        statement = body[statement_start:statement_end]
        expected_count = 3 if (word & 63) == 26 else 1
        if statement.count('cpu->gpr[18]') != expected_count:
            raise ValueError(f'Camera generated operand mismatch at {address:08X}')
        # A local value avoids repeated policy calls in DIV's quotient/remainder.
        statement = ('    { const uint32_t wide_focal = tekken3_fight_camera_focal(cpu);\n'
                     + statement.replace('cpu->gpr[18]', 'wide_focal') + '\n    }')
        body = body[:statement_start] + statement + body[statement_end:]
    return ('/* Generated by tools/build_fight_camera.py; do not edit. */\n'
            '#include "SLUS_004.02_decls.h"\n'
            '#include "tekken3_fight_camera.h"\n\n' + body)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--source', type=Path, required=True)
    parser.add_argument('--exe', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    result = generate(args.source.read_text(encoding='utf-8'), args.exe.read_bytes())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding='utf-8') != result:
        args.output.write_text(result, encoding='utf-8')
