"""Insert source-only transition dispatches without losing CPS continuations."""
import argparse
import struct
from pathlib import Path


def generate(root):
    exe=(root/'disc/SLUS_004.02').read_bytes()
    bodies=[]
    for part,func,address,opcode,hook in (
        (2,'8002DE24',0x8002DF90,0x2C620045,
         'if (tekken3_ttt1_source_condition(cpu->gpr[17], cpu->gpr[3])) cpu->gpr[2] = 1;'),
        (3,'8002F3AC',0x8002FA00,0x8623019A,
         'if (tekken3_ttt1_source_transition(cpu)) {\n'
         '#ifdef PSX_ENABLE_BLOCK_CYCLES\n    psx_cyc_bb_defer_flush();\n#endif\n'
         '    cpu->pc = 0x80030E6Cu; return;\n}'),
        (9,'8003F098',0x8003F890,0x92A300B9,
         'if (tekken3_ttt1_source_rotation(cpu->gpr[21])) cpu->gpr[3] = 13;')):
        if struct.unpack_from('<I',exe,address-0x80010000+0x800)[0]!=opcode:
            raise ValueError(f'Combat instruction mismatch at {address:08X}')
        source=(root/f'generated/SLUS_004.02_full_{part:02}.c').read_text()
        start=source.index(f'void func_{func}(CPUState* cpu)\n{{')
        end=source.index('\n}\n',start)+3
        body=source[start:end].replace(f'void func_{func}(',f'void __wrap_func_{func}(',1)
        marker=f'/* 0x{address:08X}: 0x{opcode:08X} */'
        if body.count(marker)!=1:raise ValueError('Combat generated marker mismatch')
        pos=body.index(marker)+len(marker)
        body=body[:pos]+'\n    '+hook+body[pos:]
        bodies.append(body)
    return ('/* Generated by build_ttt1_combat_hooks.py; do not edit. */\n'
            '#include "SLUS_004.02_decls.h"\n'
            'extern int tekken3_ttt1_source_transition(CPUState*);\n'
            'extern int tekken3_ttt1_source_rotation(uint32_t);\n'
            'extern int tekken3_ttt1_source_condition(uint32_t, unsigned);\n\n'+'\n'.join(bodies))


def generate_push(root):
    # Patching these instructions in guest RAM makes the transition routine
    # run in the dirty-code interpreter, bypassing its native Jun hooks.
    # Retain every overlapping alias and CPS entry in this complete shard.
    source=(root/'generated/SLUS_004.02_full_04.c').read_text()
    exe=(root/'disc/SLUS_004.02').read_bytes()
    for address in (0x800309f4,0x80030c18,0x80030d80):
        opcode=0x2442075c
        if struct.unpack_from('<I',exe,address-0x80010000+0x800)[0]!=opcode:
            raise ValueError('Pushback instruction mismatch')
        marker=f'/* 0x{address:08X}: 0x{opcode:08X} */'
        if source.count(marker)!=2:raise ValueError('Pushback alias generation changed')
        source=source.replace(marker,marker+'\n    cpu->gpr[2] = tekken3_ttt1_push_base();')
    return '#include <stdint.h>\nextern uint32_t tekken3_ttt1_push_base(void);\n'+source


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--root',type=Path,required=True)
    p.add_argument('--output',type=Path,required=True);a=p.parse_args()
    result=generate(a.root)
    if not a.output.exists() or a.output.read_text()!=result:a.output.write_text(result)
    out=a.output.with_name('tekken3_ttt1_push_generated.c');result=generate_push(a.root)
    if not out.exists() or out.read_text()!=result:out.write_text(result)
